AWS_ACCESS_KEY_ID = "AKIAX30SJ3K6FU5HUKUE"
AWS_SECRET_ACCESS_KEY = "J/Nn2nDM2pDTJ9fHWINJhnXS8JPOizOAimKXkhrh"
AWS_S3_BUCKET = "uk-building-regulations-vectorstore"
GROQ_API_KEY = "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"
